spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/microsevice_register_demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 507239721628-21ccetbmvilmnfpn7q7e4s73mvhg3g8s.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 3251837211794428
            client-secret: a58712cc7e56cd7498fe00d25bb91d41

server:
  port: 8081


